import { Injectable } from '@angular/core';
import { InMemoryDbService } from 'angular-in-memory-web-api';
import { Mariachi } from './mariachi';

@Injectable({
  providedIn: 'root',
})
export class InMemoryDataService implements InMemoryDbService {
  createDb() {
    const mariachis = [
      {
        id: 1,
        mariachiGroupName: 'Mariachi Universal',
        mariachiGroupCity: 'Los Angeles',
        mariachiGroupState: 'CA',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Dan Sobrino',
        mariachiGroupContactPhone: '562-555-4572',
        mariachiGroupContactEmail: 'universal@hotmail.com',
        mariachiGroupImageUrl: './assets/universal.png',
        mariachiGroupVideoUrl: './assets/mariachi-id0.PNG',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember: true
      },
      {
        id: 2,
        mariachiGroupName: 'Mariachi Sol de Mexico',
        mariachiGroupCity: 'Santa Anita',
        mariachiGroupState: 'CA',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Jose Hernandez',
        mariachiGroupContactPhone: '902-555-3356',
        mariachiGroupContactEmail: 'sol@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id2.jpg',
        mariachiGroupVideoUrl: './assets/mariachi-id1.JPG',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember: false
      },
      {
        id: 3,
        mariachiGroupName: 'Mariachi Las Perlitas Tapatias',
        mariachiGroupCity: 'Guadalajara',
        mariachiGroupState: 'JAL',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Nancy Rojas',
        mariachiGroupContactPhone: '896-555-8888',
        mariachiGroupContactEmail: 'perlitas@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id3.PNG',
        mariachiGroupVideoUrl: './assets/mariachi-id3.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'MEXICO',
        mariachiGroupOtherCountry: '',
        mariachiMember: true
      },
      {
        id: 4,
        mariachiGroupName: 'Mariachi Los Camperos',
        mariachiGroupCity: 'Houston',
        mariachiGroupState: 'TX',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Nati Cano',
        mariachiGroupContactPhone: '213-555-8613',
        mariachiGroupContactEmail: 'camperos@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id4.png',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember:true
      },
      {
        id: 5,
        mariachiGroupName: 'Mariachi Los Imperiales',
        mariachiGroupCity: 'Miami',
        mariachiGroupState: 'FL',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Arturo Armas',
        mariachiGroupContactPhone: '562-569-9956',
        mariachiGroupContactEmail: 'imperiales@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id5.jpg',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember: false
      },
      {
        id: 6,
        mariachiGroupName: 'Mariachi Los Palmeros',
        mariachiGroupCity: 'Fresno',
        mariachiGroupState: 'CA',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'El Muñeco',
        mariachiGroupContactPhone: '486-555-2256',
        mariachiGroupContactEmail: 'palmeros@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id6.PNG',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember: true
      },
      {
        id: 7,
        mariachiGroupName: 'Mariachi Imperial de Mexico',
        mariachiGroupCity: 'Mexico DF',
        mariachiGroupState: 'DF',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Nancy Rojas',
        mariachiGroupContactPhone: '896-555-8888',
        mariachiGroupContactEmail: 'imperialeDeMex@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id7.PNG',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'MEXICO',
        mariachiGroupOtherCountry: '',
        mariachiMember: true
      },
      {
        id: 8,
        mariachiGroupName: 'Mariachi Las Bravas de Ottawa',
        mariachiGroupCity: 'Ottawa',
        mariachiGroupState: 'ONTARIO',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Nancy Rojas',
        mariachiGroupContactPhone: '896-555-8888',
        mariachiGroupContactEmail: 'bravas@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id8.PNG',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'OTHER',
        mariachiGroupOtherCountry: 'CANADA',
        mariachiMember: true
      },
      {
        id: 9,
        mariachiGroupName: 'Mariachi de Croatia',
        mariachiGroupCity: 'Zagreb',
        mariachiGroupState: 'Croatia',
        mariachiGroupZip: '90000-CRO45',
        mariachiGroupContactName: 'Ramon Gonzalez',
        mariachiGroupContactPhone: '745-258',
        mariachiGroupContactEmail: 'mariachiCroatia@hotmail.com',
        mariachiGroupImageUrl: './assets/universal.png',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'OTHER',
        mariachiGroupOtherCountry: 'CROATIA',
        mariachiMember: true
      },
      {
        id: 10,
        mariachiGroupName: 'Mariachi Celeste',
        mariachiGroupCity: 'Los Angeles',
        mariachiGroupState: 'CA',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Dan Sobrino',
        mariachiGroupContactPhone: '562-555-4572',
        mariachiGroupContactEmail: 'universal@hotmail.com',
        mariachiGroupImageUrl: './assets/universal.png',
        mariachiGroupVideoUrl: './assets/mariachi-id0.PNG',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember: true
      },
      {
        id: 11,
        mariachiGroupName: 'Mariachi de la Paz',
        mariachiGroupCity: 'Santa Anita',
        mariachiGroupState: 'CA',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Jose Hernandez',
        mariachiGroupContactPhone: '902-555-3356',
        mariachiGroupContactEmail: 'sol@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id2.jpg',
        mariachiGroupVideoUrl: './assets/mariachi-id1.JPG',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember: false
      },
      {
        id: 12,
        mariachiGroupName: 'Mariachi Vargas',
        mariachiGroupCity: 'Guadalajara',
        mariachiGroupState: 'JAL',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Nancy Rojas',
        mariachiGroupContactPhone: '896-555-8888',
        mariachiGroupContactEmail: 'perlitas@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id3.PNG',
        mariachiGroupVideoUrl: './assets/mariachi-id3.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'MEXICO',
        mariachiGroupOtherCountry: '',
        mariachiMember: true
      },
      {
        id: 13,
        mariachiGroupName: 'Mariachi Caraepalo',
        mariachiGroupCity: 'Houston',
        mariachiGroupState: 'TX',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Nati Cano',
        mariachiGroupContactPhone: '213-555-8613',
        mariachiGroupContactEmail: 'camperos@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id4.png',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember:true
      },
      {
        id: 14,
        mariachiGroupName: 'Mariachi Los Aztecas',
        mariachiGroupCity: 'Miami',
        mariachiGroupState: 'FL',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Arturo Armas',
        mariachiGroupContactPhone: '562-569-9956',
        mariachiGroupContactEmail: 'imperiales@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id5.jpg',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember: false
      },
      {
        id: 15,
        mariachiGroupName: 'Mariachi San Luis',
        mariachiGroupCity: 'Fresno',
        mariachiGroupState: 'CA',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'El Muñeco',
        mariachiGroupContactPhone: '486-555-2256',
        mariachiGroupContactEmail: 'palmeros@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id6.PNG',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'USA',
        mariachiGroupOtherCountry: '',
        mariachiMember: true
      },
      {
        id: 16,
        mariachiGroupName: 'Mariachi Los Imperiales',
        mariachiGroupCity: 'Mexico DF',
        mariachiGroupState: 'DF',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Nancy Rojas',
        mariachiGroupContactPhone: '896-555-8888',
        mariachiGroupContactEmail: 'imperialeDeMex@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id7.PNG',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'MEXICO',
        mariachiGroupOtherCountry: '',
        mariachiMember: true
      },
      {
        id: 17,
        mariachiGroupName: 'Mariachi Los Rayos de España',
        mariachiGroupCity: 'Ottawa',
        mariachiGroupState: 'ONTARIO',
        mariachiGroupZip: '90000',
        mariachiGroupContactName: 'Nancy Rojas',
        mariachiGroupContactPhone: '896-555-8888',
        mariachiGroupContactEmail: 'bravas@hotmail.com',
        mariachiGroupImageUrl: './assets/mariachi-id8.PNG',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'OTHER',
        mariachiGroupOtherCountry: 'ESPAñA',
        mariachiMember: true
      },
      {
        id: 18,
        mariachiGroupName: 'Mariachi Cara Mia',
        mariachiGroupCity: 'Roma',
        mariachiGroupState: 'Croatia',
        mariachiGroupZip: '90000-CRO45',
        mariachiGroupContactName: 'Ramon Gonzalez',
        mariachiGroupContactPhone: '745-258',
        mariachiGroupContactEmail: 'mariachiCroatia@hotmail.com',
        mariachiGroupImageUrl: './assets/universal.png',
        mariachiGroupVideoUrl: './assets/universal.mpg',
        mariachiGroupWeb: 'http://www.sobrino.net',
        mariachiGroupCountry: 'OTHER',
        mariachiGroupOtherCountry: 'ITALIA',
        mariachiMember: true
      }      
    ];
    return {mariachis};
  }

  // Overrides the genId method to ensure that a hero always has an id.
  // If the heroes array is empty,
  // the method below returns the initial number (11).
  // if the heroes array is not empty, the method below returns the highest
  // hero id + 1.
  genId(mariachis: Mariachi[]): number {
    return mariachis.length > 0 ? Math.max(...mariachis.map(mariachi => mariachi.id)) + 1 : 10;
  }
}